Repository berty/assets, pull requests merged in 2020-11, with the labels that each got.

#45 Top Logo Animation refresh in Home
  animation/home_logorefresh_animation/home-logorefresh-gifbertyanim.gif
  animation/home_logorefresh_animation/home_berty_logo_animated.html
  animation/home_logorefresh_animation/home_berty_logo_animated.json
Labels: 🔍 Ready for Review

#47 Add files via upload : Exit Animation (on Right side of the screen)
  animation/home_logorefresh_animation/Berty20close20animation (1).html
  animation/home_logorefresh_animation/Berty_close_animation (1).json
  animation/home_logorefresh_animation/gifbertyanim-Exit.gif
Labels: ✅ Approved

#48 chore: disable imgbot
  .imgbotconfig
Labels: chore
